language: python

python:
- '3.4'

env:
- DJANGO=Django>=1.8

install:
- pip install -r requirements.txt --use-mirrors

before_script:
- python manage.py collectstatic --noinput

script: py.test --reuse-db heldev

addons:
  postgresql: "9.4"
